pipeline {
    agent any

    environment {
        FRONTEND = 'frontend'
        BACKEND = 'backend'
    }

    stages {

        stage('Checkout Source') {
            steps {
                checkout scm
            }
        }

        stage('Install Frontend Dependencies') {
            steps {
                dir("${FRONTEND}") {
                    bat 'npm install'
                }
            }
        }

        stage('Build React') {
            steps {
                dir("${FRONTEND}") {
                    bat 'npm run build'
                }
            }
        }

        stage('Install Backend Dependencies') {
            steps {
                dir("${BACKEND}") {
                    bat 'pip install -r requirements.txt'
                }
            }
        }

        stage('Run Backend') {
            steps {
                dir("${BACKEND}") {
                    bat 'python app.py'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                bat 'docker build -t innovationhub .'
            }
        }

    }

    post {
        success {
            echo 'Build Successful'
        }
        failure {
            echo 'Build Failed'
        }
    }
}
